import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';

import NavBar from './NavBar';
import AuthProvier from './auth/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <AuthProvier>
          <NavBar />
          <main className="p-5">
            <Suspense>{children}</Suspense>
          </main>
        </AuthProvier>
      </body>
    </html>
  );
}
